### PR TITLE
UE-390: fixup to banner positions

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Fixes to the responsive view of the full bleed banner
- Removed the link from the body of the card.
- Fixed the external link icon
- fixed positions of the alerts on the logged in view.
   - Check with the clearing cache
   - Check with the global message enabled.
- fixed the positions of the alerts in logged out view.

# Review By (Date)
- 11/19

# Criticality
- Normal
- Only on this subtheme

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to homepage
4. Create a full bleed banner.
4. Verify that the image looks correct in all window sizes.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- VPUE Subtheme

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/UE-391
- https://stanfordits.atlassian.net/browse/UE-390
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by jdwjdwjdw — CHANGES_REQUESTED** [review]
Images are looking much better, great job!

I'm seeing some issues with the alerts. While signed in with no global message, it appears the alert is hidden behind the admin toolbar (img 1). When the global message is added (img 2), the alert appears, though it does cover some of the global message. I wasn't sure how to test alerts while logged out - is there a situation where an alert will appear for logged out users?

Screen Shot 2021-11-18 at 12 03 56 PM

Screen Shot 2021-11-18 at 12 10 06 PM

**Comment by jenbreese** [comment]
Mine looks looks this
Screen Shot 2021-11-18 at 1 59 55 PM
.

**Comment by jenbreese** [comment]
Screen Shot 2021-11-18 at 2 02 29 PM

**Comment by jdwjdwjdw** [comment]
Per our zoom/slack conversations, let's go ahead with merging this.

**Pull request merged**
