### PR TITLE
UE-363: adding focus to the drop down menus

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Create a focus line when tabbing or clicking to a secondary navigation. 
- On the home page there is now a heavy white line above the caret
- Other pages kept the same focus since it did have one. 
- No changes to the responsive views.
- Made the border line between the link and caret a white from the grey.

# Review By (Date)
- 9/10

# Criticality
- Normal
- Accessibility

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Turn on drop down menu
4. add content in the drop downs
3. Navigate to the homepage 
4. Verify when using the keyboard, you can see the focus change on the Caret.
5. Verify that the nested menus have the default colors and behaviors. 

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- [UE-363](https://stanfordits.atlassian.net/browse/UE-363)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Review by jdwjdwjdw — COMMENTED** [review]
@jenbreese this is looking good! I am noticing that there is currently a small black border bottom applied to the drop down carets (see attached). Are those something we want to remove, keep as is, or also update to white (see attached for how that would look)?

Screen Shot 2021-09-08 at 4 35 07 PM
Screen Shot 2021-09-08 at 4 34 52 PM

**Comment by jenbreese** [comment]
@jdwjdwjdw this problem exists for the Core Product as well. @cjwest I think it is better to fix in the Core rather than the subtheme, correct? Did you make a ticket for it? I thought so but cannot find it.

**Comment by cjwest** [comment]
@jenbreese ,
I think you're thinking of other focus issues. 😁 

That underline in @jdwjdwjdw's screenshot is part of the core styles.

Screen Shot 2021-09-15 at 10 15 50 AM

For your subtheme, I think it makes sense to remove it.

**Comment by jenbreese** [comment]
Closing this PR in favor of this one: https://github.com/SU-SWS/vpue_undergrad_subtheme/pull/32

**Pull request closed without merging**
